### DISCUSSION TITLE
Issue with Running PySpark Code in Cluster Mode

### DISCUSSION THREAD

**Discussion by KAZIcodes** [mmRoshani/cloud-computing-2025#6] [Q&A] [answered]
Hi,

I encountered an issue with the Spark task in the second homework assignment. Specifically, I found that my PySpark code does not run when using deploy-mode=cluster (which distributes execution across multiple workers or containers in our case) with the following command and I also use the same spark in docker container repo mentioned in the home work descriptions:

spark-submit --deploy-mode cluster --name "FederatedAveraging" app.py

According to the Spark documentation (and as confirmed by an exception I received), Python code can only run in client mode on spark, meaning execution happens on a single machine (in our case, a single container). When running in client mode, there is no log or status update in Spark’s web UI; however, logs are accessible through the container’s terminal, and the code executes successfully.

I also attempted an approach(https://github.com/big-data-europe/docker-spark/tree/master/template/python) from this repository, which is part of the same Spark-in-Docker setup mentioned in the homework description. However, this method does pretty much the same thing and the job runs without distributing execution across worker nodes.

My questions are:
    Is the homework assignment intended for us to run the code only in client mode?
    Or are we expected to set up true cluster mode execution?
    I read that YARN can be used as a resource manager (Spark master node), but I couldn't configure it correctly within the provided Spark container setup, even though the image is built to be compatible with Hadoop.

**Comment by mmRoshani** [comment, marked as answer]
Hi Amirali, Thanks for posting your question here. I understand your confusion about the deployment modes in Spark for your homework assignment. Let me clarify some key points about Spark’s deployment modes and address your specific questions.

## Understanding Spark Deployment Modes

You’re correct about the fundamental difference between the deployment modes:

- Client mode: The driver runs on the client machine (or container) that submitted the job. Python code typically runs in this mode.
- Cluster mode: The driver runs on one of the worker nodes in the cluster.

## The Python Code Limitation

Your observation is accurate. PySpark applications have a limitation with cluster mode. When you use `--deploy-mode cluster` with Python applications, you’ll encounter issues because:

1. The Python interpreter needs to be available on all worker nodes
2. Any dependencies your Python script requires must be distributed to all workers
3. The driver program (which coordinates the execution) needs your Python code to be serialized and sent to the workers

## Regarding Your Homework Assignment

Based on your description, it appears that:

1. You’re successfully running the code in client mode
2. You’re attempting to use the big-data-europe/docker-spark setup

The template (big-data-europe) provides a way to package Python applications with Spark in Docker, but doesn’t automatically set up true distributed execution across multiple worker containers.

If the client mode satisfies you, then it is okay by me. I linked the multi-node spark for you to explore the distributed execution (which, by default, I considered using Java or Scala instead of Python).

### Regarding YARN

NOTE: This requires advanced Docker customization and is beyond the homework’s scope (do it only if you are willing to explore task distribution among workers/nodes).

Setting up YARN with the Docker containers would require additional configuration beyond the basic docker-spark setup. The Hadoop compatibility in the image doesn’t automatically configure YARN as the resource manager.

Have you done these steps for YARN setup?

#### Create Configuration Files
You’ll need minimal Hadoop/YARN configuration files. Create a directory named `hadoop-config` next to your `docker-compose.yml`.

- hadoop-config/core-site.xml

```xml
<configuration>
    <property>
        <name>fs.defaultFS</name>
        <value>hdfs://namenode:9000</value> <!-- or 9820/9870 -->
    </property>
</configuration>
```

- hadoop-config/hdfs-site.xml (for single-node HDFS)

```xml
<configuration>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
    </property>
    <!-- any other HDFS tuning properties if needed -->
</configuration>
```

- hadoop-config/yarn-site.xml

```xml
<configuration>
    <property>
        <name>yarn.resourcemanager.hostname</name>
        <value>resourcemanager</value>
    </property>
    <property>
        <name>yarn.nodemanager.aux-services</name>
        <value>mapreduce_shuffle</value> <!-- required by spark-->
    </property>
    <!-- adjust NodeManager resources as you wish-->
    <property>
        <name>yarn.nodemanager.resource.memory-mb</name>
        <value>4096</value> <!-- example: 4GB per NodeManager -->
    </property>
    <property>
        <name>yarn.nodemanager.resource.cpu-vcores</name>
        <value>2</value> <!-- example: 2 vcores per NodeManager -->
    </property>
    <!-- enable log aggregation -->
    <property>
         <name>yarn.log-aggregation-enable</name>
         <value>true</value>
    </property>
    <property>
         <name>yarn.log.server.url</name>
         <value>http://historyserver:8188/applicationhistory/logs/</value> <!-- if using history server -->
    </property>
</configuration>
```

- hadoop-config/mapred-site.xml

```xml
<configuration>
    <property>
        <name>mapreduce.framework.name</name>
        <value>yarn</value>
    </property>
    <property>
         <name>mapreduce.application.classpath</name>
         <value>$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/*:$HADOOP_MAPRED_HOME/share/hadoop/mapreduce/lib/*</value>
    </property>
</configuration>
```

#### Modify `docker-compose.yml`

```yaml
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.3.4-java8 # dedicated hadoop images (or change as needed)
    container_name: namenode
    hostname: namenode
    volumes:
      - hadoop_namenode_data:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hadoop-cluster
    ports:
      - "9870:9870" # HDFS NameNode Web UI
      # - "9000:9000" # HDFS RPC (optional to expose externally)
    networks:
      - hadoop_spark_net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.3.4-java8
    container_name: datanode
    hostname: datanode
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode_data:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    networks:
      - hadoop_spark_net

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.3.4-java8
    container_name: resourcemanager
    hostname: resourcemanager
    depends_on:
      - namenode
      - datanode
    environment:
      - SERVICE_PRECONDITION=namenode:9870 datanode:9864 # default ports for DataNode data transfer/web UI
      # NOTE: YARN config can also be passed via env if image supports it
    ports:
      - "8088:8088" # YARN ResourceManager Web UI
    volumes:
      - ./hadoop-config:/etc/hadoop/conf # mount shared config
    networks:
      - hadoop_spark_net

  nodemanager1: # you can scale this by adding nodemanager2, etc.
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.3.4-java8
    container_name: nodemanager1
    hostname: nodemanager1
    depends_on:
      - namenode
      - resourcemanager
    environment:
      - SERVICE_PRECONDITION=namenode:9870 resourcemanager:8088
      # optional: override resources per nodemanager if needed
      # - YARN_NODEMANAGER_RESOURCE_MEMORY_MB=2048
      # - YARN_NODEMANAGER_RESOURCE_CPU_VCORES=1
    volumes:
      - ./hadoop-config:/etc/hadoop/conf # mount shared config
    networks:
      - hadoop_spark_net

  # OPTIONAL: Spark History Server (recommended for viewing completed apps on YARN)  # historyserver:
  #   image: bde2020/spark-history-server:3.3.0-hadoop3.3
  #   container_name: historyserver
  #   hostname: historyserver
  #   depends_on:
  #     - resourcemanager
  #   ports:
  #     - "18080:18080"
  #   volumes:
  #     - spark_history_logs:/tmp/spark-events # needs HDFS path configured in spark-defaults
  #     - ./spark-defaults.conf:/spark/conf/spark-defaults.conf # for HDFS event log dir
  #   networks:
  #     - hadoop_spark_net

  # Spark Client container (for submitting jobs)
  spark-client:
    image: bde2020/spark-base:3.3.0-hadoop3.3 # or use spark-master/worker image if preferred https://hub.docker.com/r/bde2020/spark-master
    container_name: spark-client
    hostname: spark-client
    depends_on:
      - resourcemanager
    volumes:
      - ./hadoop-config:/etc/hadoop/conf # provide YARN config to Spark client
      - ./app.py:/app/app.py # mount your application code
      # - ./spark-defaults.conf:/spark/conf/spark-defaults.conf # optionally mount spark defaults
    networks:
      - hadoop_spark_net
    stdin_open: true
    tty: true

volumes:
  hadoop_namenode_data:
  hadoop_datanode_data:
  # spark_history_logs: # if using history server

networks:
  hadoop_spark_net:
```

#### How to Use

1. Save the configuration files (core-site.xml, etc.) in the hadoop-config directory
2. Save the docker-compose.yml file
3. Make sure your app.py is in the same directory as the docker-compose.yml
4. Start the cluster: docker-compose up -d
5. Wait for services to become healthy (check logs with docker-compose logs -f or check UIs)
6. Submit your Spark job from the spark-client container

```bash
docker-compose exec spark-client spark-submit \
    --master yarn \
    --deploy-mode client \ # or cluster, bearing in mind PySpark driver limitations
    --name "FederatedAveragingOnYarn" \
    /app/app.py
```

7. Monitor the job via the YARN ResourceManager UI: http://localhost:8088

**Important Considerations**

- PySpark Cluster Mode Limitation: As discussed before, running the PySpark driver in `--deploy-mode cluster` on <mark>**YARN still has the same fundamental limitations (needing Python/dependencies on nodes where the driver might run)**</mark>. Often, PySpark on YARN is still run with `--deploy-mode client`, where the driver runs inside the spark-client container, but the executors run distributed across the NodeManagers managed by YARN.

- Dependency Management: For cluster mode (or even client mode executors), you’ll need to manage Python dependencies. Options include:
    - Using `--py-files` to ship .py files.
    - Using `--archives` to ship a zipped virtual environment (venv.zip#environment).
    - Ensuring the required Python version and libraries are installed within the NodeManager containers.

- Resource Allocation: The memory/vcores in `yarn-site.xml` and those requested during `spark-submit` (--driver-memory, --executor-memory, --num-executors, --executor-cores) need careful tuning (in some cases with low resource cluster won't start).

- Image Versions: Ensure compatibility between Hadoop and Spark image versions. The ones used above (hadoop3.3.4, spark-3.3.0) should generally work.

- Complexity: This setup is significantly more complex than Spark Standalone, [reflecting the nature of YARN](https://emojipedia.org/emoji-mashup/twitter/twemoji-14.0?a=%F0%9F%98%96&b=%F0%9F%92%80).

Hope you fix and run it if you are interested.
